name: Vishnu
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - tqdm
    - random
    - ipywidgets
    - scipy
    - time 